version: "3.5"

services:
    app-postgres:
        image: postgres
        container_name: petflix-postgres_container
        restart: always
        environment:
         - PGDATA=/var/lib/postgresql/data/pgdata
        volumes:
         - /tmp/data:/var/lib/postgresql/data
        ports:
            - "${POSTGRES_PORT}:5432"
        env_file:
            - .env
